# Generated by Django 2.2.4 on 2020-09-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('art', models.CharField(max_length=25, null=True, verbose_name='Артикул')),
                ('full_name', models.TextField(null=True, verbose_name='Наименование полное')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('is_sale', models.BooleanField(verbose_name='Распродажа')),
                ('is_new', models.BooleanField(verbose_name='Новинка')),
                ('is_hot', models.BooleanField(verbose_name='Спецпредложение')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
    ]
