# Generated by Django 3.1.3 on 2020-11-24 06:12

from django.db import migrations, models
import django.db.models.deletion
import goodsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=goodsapp.models.get_image_name, verbose_name='Изображение 200х200')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to=goodsapp.models.get_image_name, verbose_name='Изображение 200х200')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.category', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование для магазина')),
                ('art', models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Наименование для магазина (не использовать)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Распродажа')),
                ('is_new', models.BooleanField(default=False, verbose_name='Новинка')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Спецпредложение')),
                ('is_service', models.BooleanField(default=False, verbose_name='Услуга')),
                ('is_show', models.BooleanField(default=False, verbose_name='Виден для пользователей')),
                ('uid_1c', models.SlugField(blank=True, max_length=36, null=True, verbose_name='Идентификатор в 1С')),
                ('code_1c', models.CharField(blank=True, max_length=11, null=True, verbose_name='Код 1С')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.brand', verbose_name='Бренд')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Свойство',
                'verbose_name_plural': 'Свойства',
            },
        ),
        migrations.CreateModel(
            name='PropertySetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Шаблон наборов свойств',
                'verbose_name_plural': 'Шаблоны наборов свойств',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.property', verbose_name='Свойство')),
            ],
            options={
                'verbose_name': 'Значение',
                'verbose_name_plural': 'Значения',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='template',
            field=models.ManyToManyField(blank=True, to='goodsapp.PropertySetTemplate', verbose_name='Шаблон'),
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to=goodsapp.models.get_image_name, verbose_name='Изображение 370x220')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('quant', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Период')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='GoodsPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.good', verbose_name='Номенклатура')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.property', verbose_name='Свойство')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.value', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойств',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.propertysettemplate', verbose_name='Шаблон набора свойств'),
        ),
    ]
