# Generated by Django 2.2.4 on 2020-09-23 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0002_auto_20200923_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='value',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Property', verbose_name='Свойство'),
        ),
    ]
