# Generated by Django 2.2.4 on 2020-09-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0003_auto_20200923_1503'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectPropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Good', verbose_name='Номенклатура')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Property', verbose_name='Свойство')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Value', verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Значение свойства',
                'verbose_name_plural': 'Значения свойств',
            },
        ),
    ]
