# Generated by Django 2.2.4 on 2020-09-24 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0005_auto_20200924_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectpropertyvalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Value', verbose_name='Значение'),
        ),
    ]
