# Generated by Django 2.2.4 on 2020-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0006_auto_20200924_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='art',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='good',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование полное'),
        ),
    ]
