# Generated by Django 2.2.4 on 2020-09-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0007_auto_20200924_1412'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObjectPropertyValue',
            new_name='GoodsPropertyValue',
        ),
    ]
