# Generated by Django 2.2.4 on 2020-09-25 05:42

from django.db import migrations, models
import django.db.models.deletion
import goodsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0008_auto_20200925_0830'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(blank=True, default=None, null=True, upload_to=goodsapp.models.get_image_name, verbose_name='Изображение 370x220')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
