# Generated by Django 2.2.4 on 2020-09-25 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0009_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodspropertyvalue',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goodsapp.Value', verbose_name='Значение'),
        ),
    ]
