# Generated by Django 2.2.4 on 2020-09-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0011_auto_20200925_1102'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySetTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Шаблон наборов свойств',
                'verbose_name_plural': 'Шаблоны наборов свойств',
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(to='goodsapp.Category'),
        ),
        migrations.AddField(
            model_name='property',
            name='publications',
            field=models.ManyToManyField(to='goodsapp.PropertySetTemplate'),
        ),
    ]
