# Generated by Django 2.2.4 on 2020-09-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0012_auto_20200925_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='category',
            field=models.ManyToManyField(null=True, to='goodsapp.Category', verbose_name='Категория'),
        ),
    ]
