# Generated by Django 2.2.4 on 2020-09-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0013_auto_20200925_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='publications',
        ),
        migrations.AddField(
            model_name='property',
            name='template',
            field=models.ManyToManyField(null=True, to='goodsapp.PropertySetTemplate', verbose_name='Шаблон'),
        ),
    ]
