# Generated by Django 2.2.4 on 2020-09-25 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0014_auto_20200925_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.PropertySetTemplate', verbose_name='Шаблон'),
        ),
    ]
