# Generated by Django 2.2.4 on 2020-09-25 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0015_good_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.PropertySetTemplate', verbose_name='Шаблон набора свойств'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('quant', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Период')),
                ('good', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.Good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
    ]
