# Generated by Django 3.1.1 on 2020-09-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0018_auto_20200928_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='good',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='value',
            name='slug',
        ),
        migrations.AddField(
            model_name='good',
            name='uid_1c',
            field=models.SlugField(blank=True, max_length=36, null=True, verbose_name='Идентификаторв в 1С'),
        ),
    ]
