# Generated by Django 2.2.4 on 2020-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0020_auto_20200929_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование для магазина'),
        ),
    ]
