# Generated by Django 3.1.1 on 2020-10-01 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0021_auto_20200930_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.category', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='good',
            name='code_1c',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Код 1С'),
        ),
        migrations.RemoveField(
            model_name='good',
            name='category',
        ),
        migrations.AddField(
            model_name='good',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='goodsapp.category', verbose_name='Категория'),
        ),
    ]
