# Generated by Django 2.2.4 on 2020-10-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0022_auto_20201001_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='is_show',
            field=models.BooleanField(default=False, verbose_name='Виден для пользователей'),
        ),
    ]
