# Generated by Django 3.1.1 on 2020-10-07 06:58

from django.db import migrations, models
import goodsapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0023_good_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=goodsapp.models.get_image_name, verbose_name='Изображение 200х200'),
        ),
    ]
