# Generated by Django 3.0.4 on 2020-10-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0026_auto_20201008_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Url'),
        ),
    ]
