# Generated by Django 3.0.5 on 2020-10-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0027_auto_20201008_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='site_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование для магазина'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='good',
            name='full_name',
            field=models.TextField(blank=True, null=True, verbose_name='Наименование для магазина (не использовать)'),
        ),
        migrations.AlterField(
            model_name='good',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Url'),
        ),
        migrations.AlterField(
            model_name='good',
            name='uid_1c',
            field=models.SlugField(blank=True, max_length=36, null=True, verbose_name='Идентификатор в 1С'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, verbose_name='Url'),
        ),
    ]
