# Generated by Django 3.1.1 on 2020-10-09 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0028_auto_20201009_1055'),
        ('goodsapp', '0028_auto_20201008_1749'),
    ]

    operations = [
    ]
