# Generated by Django 3.1.2 on 2020-10-09 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0028_auto_20201009_1233'),
        ('goodsapp', '0028_auto_20201009_1055'),
    ]

    operations = [
    ]
