# Generated by Django 3.1.1 on 2020-10-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goodsapp', '0029_merge_20201009_1208'),
        ('goodsapp', '0029_merge_20201009_1233'),
    ]

    operations = [
    ]
