# Generated by Django 5.2.1 on 2025-05-31 06:54

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Наименование полное')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Превью)')),
                ('image1', models.ImageField(upload_to='images/', verbose_name='Изображение 1')),
                ('image2', models.ImageField(upload_to='images/', verbose_name='Изображение 2')),
                ('image3', models.ImageField(upload_to='images/', verbose_name='Изображение 3')),
                ('image4', models.ImageField(upload_to='images/', verbose_name='Изображение 4')),
                ('not_active', models.BooleanField(default=False, verbose_name='Не активный')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog_app.category')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('active_items', django.db.models.manager.Manager()),
            ],
        ),
    ]
