# Generated by Django 5.2.1 on 2025-05-31 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='seo_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<description>'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<keywords>'),
        ),
        migrations.AddField(
            model_name='catalog',
            name='seo_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<title>'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<description>'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_keywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<keywords>'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.TextField(blank=True, default='', null=True, verbose_name='<title>'),
        ),
    ]
