# Generated by Django 5.2.1 on 2025-05-31 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_alter_catalog_category_alter_catalog_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalog',
            new_name='Good',
        ),
    ]
