# Generated by Django 5.2.1 on 2025-05-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_rename_catalog_good'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Котегории'},
        ),
        migrations.AlterModelOptions(
            name='good',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='good',
            name='art',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, null=True, verbose_name='Артикул'),
        ),
        migrations.AddField(
            model_name='good',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, null=True, verbose_name='Артикул'),
        ),
    ]
