# Generated by Django 5.2.1 on 2025-05-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0005_alter_category_options_alter_good_options_good_art_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='good',
            name='code',
            field=models.CharField(blank=True, db_index=True, default='', max_length=11, null=True, verbose_name='Код (для 1С)'),
        ),
    ]
