# Generated by Django 5.2.1 on 2025-06-03 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0008_producer_alter_category_options_good_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='catalog_app.category', verbose_name='Родитель'),
        ),
    ]
