# Generated by Django 5.2.1 on 2025-10-24 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0010_remove_category_image_remove_good_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('name', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Наименование')),
                ('property', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Характеристика')),
                ('okei', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Характеристика')),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Характеристика')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='catalog_app.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
    ]
