# Generated by Django 5.2.1 on 2026-02-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0011_propertyitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='okei',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Ед.'),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='property',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Значение'),
        ),
    ]
