# Generated by Django 3.0.5 on 2020-12-13 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0002_auto_20201213_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=1024, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
