# Generated by Django 3.1.4 on 2020-12-08 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlistapp', '0003_auto_20201208_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlistapp.wishlist', verbose_name='Избранное'),
        ),
    ]
