# Generated by Django 3.1.4 on 2020-12-09 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0008_auto_20201206_1116'),
        ('wishlistapp', '0004_auto_20201208_1459'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='WishListItem',
        ),
    ]
