# Generated by Django 3.1.3 on 2020-11-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogapp.category', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='art',
            field=models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Артикул'),
        ),
    ]
