# Generated by Django 3.1.4 on 2020-12-05 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_auto_20201130_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=300, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.AlterField(
            model_name='offer',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.good', verbose_name='Номенклатура'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('review', models.CharField(max_length=1024, verbose_name='Отзыв')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка 1-5')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата отзыва')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogapp.country', verbose_name='Страна'),
        ),
    ]
