# Generated by Django 3.1.4 on 2020-12-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0004_auto_20201205_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodspropertyvalue',
            name='is_main',
            field=models.BooleanField(default=True, verbose_name='Основное'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Оценка 1-5'),
        ),
    ]
