# Generated by Django 3.1.3 on 2020-12-06 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_auto_20201205_0803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='main_image',
            new_name='is_main',
        ),
    ]
