# Generated by Django 3.1.3 on 2020-12-06 06:34

import catalogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0006_auto_20201206_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='images',
        ),
        migrations.AddField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=catalogapp.models.get_image_name, verbose_name='Изображение 500x500'),
        ),
    ]
