# Generated by Django 3.1.4 on 2020-12-09 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0008_auto_20201206_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='quant',
        ),
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(verbose_name='Период'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Период')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.good', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
            },
        ),
    ]
