# Generated by Django 3.1.4 on 2020-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0009_auto_20201209_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='good',
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='good',
            name='quant',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество'),
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
