# Generated by Django 3.0.5 on 2020-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0010_auto_20201210_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='depth',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Глубина, см'),
        ),
        migrations.AddField(
            model_name='good',
            name='height',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Высота, см'),
        ),
        migrations.AddField(
            model_name='good',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3'),
        ),
        migrations.AddField(
            model_name='good',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='good',
            name='width',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=15, verbose_name='Ширина, см'),
        ),
    ]
