# Generated by Django 3.1.3 on 2020-12-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0013_auto_20201217_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='email',
        ),
    ]
