# Generated by Django 3.1.4 on 2021-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0014_auto_20201217_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='quant',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
