# Generated by Django 3.0.5 on 2020-12-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogapp', '0010_auto_20201210_1034'),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма заказа')),
                ('comment', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Комментарий')),
                ('uid_1c', models.SlugField(blank=True, max_length=36, null=True, verbose_name='Идентификатор в 1С')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authapp.Buyer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogapp.Good', verbose_name='Номенклатура')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderapp.Order', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
            },
        ),
    ]
