# Generated by Django 3.0.5 on 2020-12-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('AW', 'Ожидает подтверждения'), ('GT', 'Собирается'), ('TF', 'Передан'), ('DL', 'Доставлен'), ('RT', 'Вернулся')], default='AW', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NP', 'Ожидает оплаты'), ('PP', 'Частично оплачен'), ('AP', 'Оплачен полностью')], default='NP', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='uid_1c',
            field=models.SlugField(blank=True, default='', max_length=36, null=True, verbose_name='Идентификатор в 1С'),
        ),
    ]
