# Generated by Django 3.0.5 on 2020-12-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20201213_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('AW', 'Ожидает подтверждения'), ('GT', 'Собирается'), ('TF', 'Передан'), ('DL', 'Доставлен'), ('RT', 'Вернулся')], default='AW', max_length=2, verbose_name='Состояние доставки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('NP', 'Ожидает оплаты'), ('PP', 'Частично оплачен'), ('AP', 'Оплачен полностью')], default='NP', max_length=2, verbose_name='Состояние оплаты'),
        ),
    ]
