# Generated by Django 3.0.5 on 2020-12-13 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0004_orderitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3'),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='volume',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15, verbose_name='Объем, м3'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Вес, кг'),
        ),
    ]
