# Generated by Django 3.1.4 on 2021-01-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_auto_20201216_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quant',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
    ]
