# Generated by Django 3.1.2 on 2021-11-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0008_order_payment_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_form',
            field=models.CharField(choices=[('AW', 'Онлайн'), ('BN', 'Безналичные'), ('NL', 'Наличные')], default='ON', max_length=2, verbose_name='Форма оплаты'),
        ),
    ]
