# Generated by Django 3.1.2 on 2021-11-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_auto_20211110_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartments',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Кв.'),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='order',
            name='floor',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Этаж'),
        ),
        migrations.AddField(
            model_name='order',
            name='house',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='order',
            name='locality',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Нас. пункт'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='order',
            name='porch',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='Индекс'),
        ),
    ]
