# Generated by Django 3.1.2 on 2021-11-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_auto_20211110_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Отчество'),
        ),
    ]
