# Generated by Django 3.1.2 on 2021-11-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0011_order_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='company_inn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН компании'),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Наименование компании'),
        ),
    ]
