# Generated by Django 3.1.2 on 2021-11-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_auto_20211110_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('AW', 'Доставка до адреса'), ('SL', 'Самовывоз')], default='DL', max_length=2, verbose_name='Тип доставки'),
        ),
    ]
